version: '3'

networks:
  lnpm:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lnpm

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./datastore/mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lnpm

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./../src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - lnpm

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: "mysql"
      PMA_PASSWORD: "root"
    restart: unless-stopped
    networks:
      - lnpm
  